# Generated by Django 4.0.6 on 2024-05-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0003_pais'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
