# Generated by Django 4.0.6 on 2024-06-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0009_remove_director_foto_director_fotod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='fotoD',
        ),
        migrations.AddField(
            model_name='director',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='directores'),
        ),
    ]
