# Generated by Django 5.0.6 on 2024-07-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0011_cine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='estado',
            field=models.BooleanField(),
        ),
    ]
